# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_auto_20160321_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreference',
            name='pep',
            field=models.PositiveIntegerField(blank=True, help_text='Номер предложения по улучшению Питона, связанного с этой статьёй, например: <i>8</i> для PEP-8', null=True, verbose_name='PEP'),
        ),
        migrations.AddField(
            model_name='reference',
            name='pep',
            field=models.PositiveIntegerField(blank=True, help_text='Номер предложения по улучшению Питона, связанного с этой статьёй, например: <i>8</i> для PEP-8', null=True, verbose_name='PEP'),
        ),
        migrations.AlterField(
            model_name='version',
            name='text_src',
            field=models.TextField(help_text='Обзорное, более полное описание нововведений и изменений, произошедших в версии. <strong>Без обозначения личного отношения. Личное отношение можно выразить в Обсуждениях к материалу.</strong>', verbose_name='Исходный текст'),
        ),
    ]
