# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_auto_20160908_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, default='', help_text='Имя в Twitter.', max_length=100, verbose_name='Twitter'),
        ),
    ]
