# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 05:45
from __future__ import unicode_literals

import apps.generics.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_auto_20160913_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Краткое имя для URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.generics.models.get_upload_to, verbose_name='Обложка')),
                ('year', models.CharField(blank=True, max_length=10, null=True, verbose_name='Год')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_published', models.DateTimeField(editable=False, null=True, verbose_name='Дата публикации')),
                ('time_modified', models.DateTimeField(editable=False, null=True, verbose_name='Дата редактирования')),
                ('supporters_num', models.PositiveIntegerField(default=0, verbose_name='Поддержка')),
                ('num', models.PositiveIntegerField(verbose_name='Номер')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Действует'), (3, 'Отозвано [автором]'), (4, 'Отложено'), (5, 'Отклонено'), (6, 'Утверждено (принято; возможно не реализовано)'), (7, 'Финализировано (работа завершена; реализовано)'), (8, 'Заменено (имеется более актуальное PEP)'), (9, 'Розыгрыш на 1 апреля')], default=1, verbose_name='Статус')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Процесс'), (2, 'Стандарт'), (3, 'Информация')], default=2, verbose_name='Тип')),
                ('last_editor', models.ForeignKey(blank=True, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pep_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
                ('linked', models.ManyToManyField(blank=True, help_text='Выберите объекты, имеющие отношение к данному.', related_name='_pep_linked_+', to='apps.PEP', verbose_name='Связанные объекты')),
                ('replaces', models.ManyToManyField(related_name='_pep_replaces_+', to='apps.PEP', verbose_name='Поглощает')),
                ('requires', models.ManyToManyField(related_name='_pep_requires_+', to='apps.PEP', verbose_name='Зависит от')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pep_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('superseded', models.ManyToManyField(related_name='_pep_superseded_+', to='apps.PEP', verbose_name='Заменено на')),
            ],
            options={
                'verbose_name_plural': 'Список PEP',
                'verbose_name': 'PEP',
            },
        ),
        migrations.AlterField(
            model_name='version',
            name='title',
            field=models.CharField(help_text='Номер версии с двумя обязательными разрядами и третим опциональным. Например: 2.7.12, 3.6.', max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pep',
            name='versions',
            field=models.ManyToManyField(related_name='peps', to='apps.Version', verbose_name='Версии Питона'),
        ),
    ]
