# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_auto_20160921_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pep',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
