# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_auto_20160921_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pep',
            name='replaces',
            field=models.ManyToManyField(related_name='replaced_by', to='apps.PEP', verbose_name='Поглощает'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='requires',
            field=models.ManyToManyField(related_name='used_by', to='apps.PEP', verbose_name='Зависит от'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='superseded',
            field=models.ManyToManyField(related_name='supersedes', to='apps.PEP', verbose_name='Заменено на'),
        ),
    ]
