# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 13:53
from __future__ import unicode_literals

import apps.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import etc.models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_auto_20160921_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_src', models.TextField(verbose_name='Исходный текст')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_published', models.DateTimeField(editable=False, null=True, verbose_name='Дата публикации')),
                ('time_modified', models.DateTimeField(editable=False, null=True, verbose_name='Дата редактирования')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус')),
                ('supporters_num', models.PositiveIntegerField(default=0, verbose_name='Поддержка')),
                ('name', models.CharField(blank=True, max_length=90, verbose_name='Имя')),
                ('name_en', models.CharField(blank=True, max_length=90, verbose_name='Имя англ.')),
                ('aka', models.CharField(blank=True, max_length=255, verbose_name='Другие имена')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
            },
            bases=(apps.models.UtmReady, etc.models.InheritedModel, models.Model),
        ),
        migrations.AlterModelOptions(
            name='pep',
            options={'verbose_name': 'PEP', 'verbose_name_plural': 'PEP'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='community',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalcommunity',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicaldiscussion',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalvideo',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='replaces',
            field=models.ManyToManyField(blank=True, related_name='replaced_by', to='apps.PEP', verbose_name='Поглощает'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='requires',
            field=models.ManyToManyField(blank=True, related_name='used_by', to='apps.PEP', verbose_name='Зависит от'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='superseded',
            field=models.ManyToManyField(blank=True, related_name='supersedes', to='apps.PEP', verbose_name='Заменено на'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='versions',
            field=models.ManyToManyField(blank=True, related_name='peps', to='apps.Version', verbose_name='Версии Питона'),
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (5, 'К отложенной публикации'), (3, 'Удален'), (4, 'В архиве')], default=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='person',
            name='last_editor',
            field=models.ForeignKey(blank=True, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
