# Generated by Django 3.0.2 on 2020-01-18 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitecats', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('apps', '0043_auto_20180603_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sitecats.category',),
        ),
        migrations.AlterField(
            model_name='article',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='article_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='book',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='community',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='community_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='event',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='externalresource_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='submitter',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='submitter',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='historicalcommunity',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalcommunity',
            name='place',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Для географически локализованных сообществ можно указать место (страна, город, село).<br>Например: «Россия, Новосибирск» или «Новосибирск», но не «Нск».', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.Place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='historicalcommunity',
            name='submitter',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='historicaldiscussion',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.ContentType', verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='historicaldiscussion',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicaldiscussion',
            name='submitter',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='place',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Укажите место проведения мероприятия.<br><b>Конкретный адрес следует указывать в описании.</b><br>Например: «Россия, Новосибирск» или «Новосибирск», но не «Нск».', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.Place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='submitter',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='submitter',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Укажите родительский раздел. Например, для модуля можно указать раздел справки, в которому он относится; для метода &#8212; класс.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.Reference', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='submitter',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='version_added',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Версия Python, для которой впервые стала актульна данная статья<br>(версия, где впервые появился модуль, пакет, класс, функция).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.Version', verbose_name='Добавлено в'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='version_deprecated',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Версия Python, для которой впервые данная статья перестала быть актуальной<br>(версия, где модуль, пакет, класс, функция были объявлены устаревшими).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.Version', verbose_name='Устарело в'),
        ),
        migrations.AlterField(
            model_name='historicalvideo',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalvideo',
            name='submitter',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pep_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='person',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='place',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='place_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reference_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='summary_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='user',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='version',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='version_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='video',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
    ]
