# Generated by Django 3.0.2 on 2020-01-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0044_auto_20200118_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='data_items',
            field=models.TextField(verbose_name='Текущие элементы сводки'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='data_result',
            field=models.TextField(help_text='Данные для фильтрации элементов сводки при последующих обращениях к ресурсу.', verbose_name='Результат для фильтрации сводки'),
        ),
    ]
