# Generated by Django 3.0.3 on 2020-02-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0045_auto_20200125_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='community',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='event',
            name='specialization',
            field=models.PositiveIntegerField(choices=[(1, 'Только Python'), (2, 'В основном Python'), (3, 'Есть секция/отделение про Python'), (4, 'Есть упоминания про Python')], default=1, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Встреча'), (2, 'Лекция'), (3, 'Конференция'), (4, 'Спринт')], default=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalcommunity',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicaldiscussion',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='specialization',
            field=models.PositiveIntegerField(choices=[(1, 'Только Python'), (2, 'В основном Python'), (3, 'Есть секция/отделение про Python'), (4, 'Есть упоминания про Python')], default=1, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Встреча'), (2, 'Лекция'), (3, 'Конференция'), (4, 'Спринт')], default=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicalvideo',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Черновик'), (2, 'Опубликован'), (3, 'Удален'), (4, 'В архиве'), (5, 'К отложенной публикации')], default=1, verbose_name='Статус'),
        ),
    ]
