# Generated by Django 3.0.3 on 2020-02-24 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0046_auto_20200223_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lnk_vacancy', to='apps.Place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='url_site',
            field=models.URLField(blank=True, null=True, verbose_name='Страница в сети'),
        ),
    ]
