# Generated by Django 3.0.3 on 2020-02-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0048_auto_20200224_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='src_alias',
            field=models.CharField(blank=True, choices=[('hh', 'hh.ru')], max_length=20, null=True, verbose_name='Идентификатор источника'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='src_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID в источнике'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='src_place_id',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='ID места в источнике'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='src_place_name',
            field=models.CharField(default='', max_length=255, verbose_name='Название места в источнике'),
        ),
    ]
