# Generated by Django 3.0.3 on 2020-02-24 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0049_auto_20200224_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='src_alias',
            field=models.CharField(blank=True, choices=[('pyglob', 'Официальный календарь'), ('pyuser', 'Календарь сообществ')], max_length=20, null=True, verbose_name='Идентификатор источника'),
        ),
        migrations.AddField(
            model_name='event',
            name='src_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID в источнике'),
        ),
        migrations.AddField(
            model_name='event',
            name='src_place_id',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='ID места в источнике'),
        ),
        migrations.AddField(
            model_name='event',
            name='src_place_name',
            field=models.CharField(default='', max_length=255, verbose_name='Название места в источнике'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='src_alias',
            field=models.CharField(blank=True, choices=[('pyglob', 'Официальный календарь'), ('pyuser', 'Календарь сообществ')], max_length=20, null=True, verbose_name='Идентификатор источника'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='src_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID в источнике'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='src_place_id',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='ID места в источнике'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='src_place_name',
            field=models.CharField(default='', max_length=255, verbose_name='Название места в источнике'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fee',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Участие платное'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lnk_event', to='apps.Place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_src',
            field=models.TextField(verbose_name='Исходный текст'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='fee',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Участие платное'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='place',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apps.Place', verbose_name='Место'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together=set(),
        ),
    ]
