# Generated by Django 3.0.3 on 2020-02-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0050_auto_20200224_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='src_place_id',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='ID места в источнике'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Встреча'), (2, 'Конференция'), (3, 'Лекция'), (4, 'Спринт')], default=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='src_place_id',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='ID места в источнике'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Встреча'), (2, 'Конференция'), (3, 'Лекция'), (4, 'Спринт')], default=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='src_place_id',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='ID места в источнике'),
        ),
    ]
