# Generated by Django 3.0.3 on 2020-02-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0051_auto_20200225_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalcommunity',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicaldiscussion',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalvideo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(help_text='Здесь следует указать название раздела справки или пакета, модуля, класса, метода, функции и т.п.', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='version',
            name='title',
            field=models.CharField(help_text='Номер версии с двумя обязательными разрядами и третим опциональным. Например: 2.7.12, 3.6.', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('src_alias', 'src_id')},
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('src_alias', 'src_id')},
        ),
    ]
