# Generated by Django 3.0.4 on 2020-04-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0052_auto_20200228_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='current',
        ),
        migrations.AddField(
            model_name='version',
            name='date_till',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание поддержки'),
        ),
    ]
