# Generated by Django 3.0.5 on 2020-04-21 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('apps', '0053_auto_20200404_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='article_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='article_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='book_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='book_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='community',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='community_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='community',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Для географически локализованных сообществ можно указать место (страна, город, село).<br>Например: «Россия, Новосибирск» или «Новосибирск», но не «Нск».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='apps.Place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='community',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='community_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_discussions', to='contenttypes.ContentType', verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='discussion_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='discussion_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='event_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lnk_event', to='apps.Place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='event',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='event_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='externalresource_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='externalresource_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalcommunity',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicaldiscussion',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='historicalvideo',
            name='last_editor',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pep_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='pep_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='person_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='person',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='person_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='place',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='place_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='place',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='place_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reference_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Укажите родительский раздел. Например, для модуля можно указать раздел справки, в которому он относится; для метода &#8212; класс.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='apps.Reference', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reference_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='version_added',
            field=models.ForeignKey(blank=True, help_text='Версия Python, для которой впервые стала актульна данная статья<br>(версия, где впервые появился модуль, пакет, класс, функция).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_added', to='apps.Version', verbose_name='Добавлено в'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='version_deprecated',
            field=models.ForeignKey(blank=True, help_text='Версия Python, для которой впервые данная статья перестала быть актуальной<br>(версия, где модуль, пакет, класс, функция были объявлены устаревшими).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_deprecated', to='apps.Version', verbose_name='Устарело в'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='summary_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='summary_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Место вашего пребывания (страна, город, село).<br>Например: «Россия, Новосибирск» или «Новосибирск», но не «Нск».', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='apps.Place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='user',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vacancy_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lnk_vacancy', to='apps.Place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vacancy_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='version',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='version_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='version',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='version_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='video',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='video_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='video',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='video_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
    ]
