# Generated by Django 4.1.7 on 2023-04-20 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('apps', '0057_auto_20210523_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalapp',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Приложение', 'verbose_name_plural': 'historical Приложения'},
        ),
        migrations.AlterModelOptions(
            name='historicalarticle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Статья', 'verbose_name_plural': 'historical Статьи'},
        ),
        migrations.AlterModelOptions(
            name='historicalbook',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Книга', 'verbose_name_plural': 'historical Книги'},
        ),
        migrations.AlterModelOptions(
            name='historicalcommunity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Сообщество', 'verbose_name_plural': 'historical Сообщества'},
        ),
        migrations.AlterModelOptions(
            name='historicaldiscussion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Обсуждение', 'verbose_name_plural': 'historical Обсуждения'},
        ),
        migrations.AlterModelOptions(
            name='historicalevent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Событие', 'verbose_name_plural': 'historical События'},
        ),
        migrations.AlterModelOptions(
            name='historicalplace',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Место', 'verbose_name_plural': 'historical Места'},
        ),
        migrations.AlterModelOptions(
            name='historicalreference',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Статья справочника', 'verbose_name_plural': 'historical Справочник'},
        ),
        migrations.AlterModelOptions(
            name='historicalvideo',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Видео', 'verbose_name_plural': 'historical Видео'},
        ),
        migrations.AlterField(
            model_name='app',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='app',
            name='linked',
            field=models.ManyToManyField(blank=True, help_text='Выберите объекты, имеющие отношение к данному.', to='apps.app', verbose_name='Связанные объекты'),
        ),
        migrations.AlterField(
            model_name='app',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='article',
            name='linked',
            field=models.ManyToManyField(blank=True, help_text='Выберите объекты, имеющие отношение к данному.', to='apps.article', verbose_name='Связанные объекты'),
        ),
        migrations.AlterField(
            model_name='article',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='linked',
            field=models.ManyToManyField(blank=True, help_text='Выберите объекты, имеющие отношение к данному.', to='apps.book', verbose_name='Связанные объекты'),
        ),
        migrations.AlterField(
            model_name='book',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='community',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='community',
            name='linked',
            field=models.ManyToManyField(blank=True, help_text='Выберите объекты, имеющие отношение к данному.', to='apps.community', verbose_name='Связанные объекты'),
        ),
        migrations.AlterField(
            model_name='community',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_discussions', to='contenttypes.contenttype', verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='linked',
            field=models.ManyToManyField(blank=True, help_text='Выберите объекты, имеющие отношение к данному.', to='apps.discussion', verbose_name='Связанные объекты'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='linked',
            field=models.ManyToManyField(blank=True, help_text='Выберите объекты, имеющие отношение к данному.', to='apps.event', verbose_name='Связанные объекты'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lnk_%(class)s', to='apps.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='event',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='externalresource',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='historicalapp',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcommunity',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldiscussion',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalplace',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalreference',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalvideo',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='partnerlink',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_partner_links', to='contenttypes.contenttype', verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='linked',
            field=models.ManyToManyField(blank=True, help_text='Выберите объекты, имеющие отношение к данному.', to='apps.pep', verbose_name='Связанные объекты'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='person',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='place',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='place',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='linked',
            field=models.ManyToManyField(blank=True, help_text='Выберите объекты, имеющие отношение к данному.', to='apps.reference', verbose_name='Связанные объекты'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='version_added',
            field=models.ForeignKey(blank=True, help_text='Версия Python, для которой впервые стала актульна данная статья<br>(версия, где впервые появился модуль, пакет, класс, функция).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_added', to='apps.version', verbose_name='Добавлено в'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='version_deprecated',
            field=models.ForeignKey(blank=True, help_text='Версия Python, для которой впервые данная статья перестала быть актуальной<br>(версия, где модуль, пакет, класс, функция были объявлены устаревшими).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deprecated', to='apps.version', verbose_name='Устарело в'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_public',
            field=models.BooleanField(db_index=True, default=False, help_text='Если выключить, то увидеть ваш профиль сможете только вы.<br>В списках пользователей профиль значиться тоже не будет.', verbose_name='Публичный профиль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lnk_%(class)s', to='apps.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='version',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='version',
            name='linked',
            field=models.ManyToManyField(blank=True, help_text='Выберите объекты, имеющие отношение к данному.', to='apps.version', verbose_name='Связанные объекты'),
        ),
        migrations.AlterField(
            model_name='version',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='video',
            name='last_editor',
            field=models.ForeignKey(blank=True, default=1, help_text='Пользователь, последним отредактировавший объект.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_editors', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='video',
            name='linked',
            field=models.ManyToManyField(blank=True, help_text='Выберите объекты, имеющие отношение к данному.', to='apps.video', verbose_name='Связанные объекты'),
        ),
        migrations.AlterField(
            model_name='video',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_submitters', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
    ]
