# Generated by Django 4.1.7 on 2023-04-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0058_preferences_alter_historicalapp_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socks5_proxy', models.TextField(default='')),
                ('google_api_key', models.TextField(default='not_a_secret')),
                ('yandex_search_id', models.TextField(default='not_a_secret')),
                ('telegram_bot_token', models.TextField(default='not_a_secret')),
                ('telegram_group', models.TextField(default='group_id or @channel_name')),
                ('vk_access_token', models.TextField(default='not_a_secret')),
                ('vk_group', models.TextField(default='group id prefixed with -')),
            ],
            options={
                'verbose_name': 'Preference',
                'verbose_name_plural': 'Preferences',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='comments_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='disqus_category_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='disqus_shortname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
    ]
