# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_user_twitter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('-date',), 'verbose_name': 'Версия Python', 'verbose_name_plural': 'Версии Python'},
        ),
        migrations.AddField(
            model_name='version',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выпуска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='version',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Текущая'),
        ),
        migrations.AlterField(
            model_name='version',
            name='title',
            field=models.CharField(help_text='Например: 2.7.12, 3.6.0', max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
