# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_auto_20161230_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='pep',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='peps', to='apps.Person', verbose_name='Авторы'),
        ),
    ]
