# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0040_auto_20161231_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books', to='apps.Person', verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='video',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='videos', to='apps.Person', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='Предпочтительно имя и фамилия. Можно указать несколько, разделяя запятыми.', max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='event',
            name='specialization',
            field=models.PositiveIntegerField(choices=[(1, 'Только Python'), (4, 'В основном Python'), (2, 'Есть секция/отделение про Python'), (3, 'Есть упоминания про Python')], default=1, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='author',
            field=models.CharField(help_text='Предпочтительно имя и фамилия. Можно указать несколько, разделяя запятыми.', max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='specialization',
            field=models.PositiveIntegerField(choices=[(1, 'Только Python'), (4, 'В основном Python'), (2, 'Есть секция/отделение про Python'), (3, 'Есть упоминания про Python')], default=1, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='historicalvideo',
            name='author',
            field=models.CharField(help_text='Предпочтительно имя и фамилия. Можно указать несколько, разделяя запятыми.', max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.CharField(help_text='Предпочтительно имя и фамилия. Можно указать несколько, разделяя запятыми.', max_length=255, verbose_name='Автор'),
        ),
    ]
